### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by wedens** [agrafix/Spock-digestive#3]
I have a very simple form (`digestive-bootstrap`) with some validation:

``` haskell
newUserForm :: Monad m => F.Form H.Html m NewUserRequest
newUserForm = NewUserRequest
              <$> "username" F..: nonEmptyText
              <*> (fst <$> newPasswordForm)
              <*> "is_admin" F..: F.bool (Just False)
   where
    nonEmptyText =
      F.check "Cannot be empty" (not . T.null) $ F.text Nothing
    newPasswordForm = F.check "Passwords don't match" (Prelude.uncurry (==)) $ (,)
      <$> "password" F..: F.text Nothing
      <*> "password2" F..: F.text Nothing

newUserFormSpec :: F.FormMeta
newUserFormSpec =
  F.FormMeta
    { F.fm_method = POST
    , F.fm_target = "/newUser"
    , F.fm_elements =
        [ F.FormElement "username" (Just "Username") F.InputText
        , F.FormElement "password" (Just "Password") F.InputPassword
        , F.FormElement "password2" (Just "Confirm password") F.InputPassword
        , F.FormElement "is_admin" (Just "Admin?") F.InputCheckbox
        ]
    , F.fm_submitText = "New User"
    }

```

then I use Spock-digestive to run this form

``` haskell
do
  let formView = F.renderForm newUserFormSpec
  f <- F.runForm "newUserForm" newUserForm
  case f of
    (view, Nothing) -> site $ formView view
    (view, Just nuReq) -> ...
```

When I type different passwords, form is failed, but no errors shown. `nonEmptyText` validator works though.

Versions: Spock-digestive-0.2.0.0, digestive-bootstrap-0.1.0.1, digestive-functors-0.8.0.1

**Comment by agrafix** [comment]
What do you mean by "form is failed"? Can you show the contents of the "view" using `print` or something?

**Comment by wedens** [comment]
@agrafix I mean result is `Nothing`. I tried to use `show` on `view` but got some absent `Show` instance error. I'll try again a bit later.

offtopic: is there some irc channel or mail list for questions about spock?

**Comment by agrafix** [comment]
Currently there's no mailing list or irc channel, but a mailing list is probably a good idea. I'll have to find some time to set it up...

**Comment by wedens** [comment]
I've tried again and I can see the error when I use `childErrors "" view`. so probably it's something `digestive-bootstrap` specific

**Comment by agrafix** [comment]
The code currently uses `errors` (see https://github.com/agrafix/digestive-bootstrap/blob/a1da22450f3d88c333c697fac30bd95b800ff912/src/Text/Digestive/Bootstrap.hs#L72). Reading the docs, probably `childErrors` seems better. Would you like to try it out and send a PR to `digestive-bootstrap` if that solves to problem for you?

**Comment by agrafix** [comment]
closed due to inactivity
